### ISSUE TITLE
`man(1)` from `man-db` doesn't like space between `-T` and `html`

### ISSUE THREAD

**Issue by kseistrup** [dillo-browser/dillo-plugin-man#1]
`man(1)` v2.12.1 from [man-db](https://gitlab.com/man-db/man-db "Tools for reading manual pages") doesn't like the `SPACE` between `-T` and `html` in `man -T html $manpage | […]`:

Instead of showing a HTML-formatted man-page, I see something that looks like PostScript.

When I edit the `man.filter.dpi` to use `man -Thtml` the plugin works as expected.

**Comment by rodarima** [comment]
Thanks, could you make a PR?

**Comment by kseistrup** [comment]
> Thanks, could you make a PR?

In order to delete a single SPACE? I'm afraid I will have to decline that request.

**Comment by rodarima** [comment]
> > Thanks, could you make a PR?
> 
> In order to delete a single SPACE? I'm afraid I will have to decline that request.

I don't have any problem fixing this (or #2) myself, the reason I ask you to fix it is so the fix is attributed to you in the git log, as I assume you already fixed it for your tree.

**Comment by kseistrup** [comment]
I don't need an attribute for deleting a single space (or two dollar signs). I just edited the shellscript locally after installing it. You needn't even mention my name.

**Comment by tkapias** [comment]
Thanks, I had the same issue.

On the same subject I had one more issue with arguments, because I force man/groff to output in color with a system-wide variable:

```bash
MANROFFOPT=-P -c
```

But, man does not like that when converting and dillo-plugin-man fail even if dillo is lauched with an empty variable declared.

So I added `unset MANROFFOPT` just above `man -Thtml $manpage ` in man.filter.dpi.

It may be useful for others, and you don't need to attribute anything to me if you use it also.

**Comment by kseistrup** [comment]
> you don't need to attribute anything to me if you use it also

I was thinking about the attributes: If it is important to some that due attributions are given, the issue can be closed with e.g. “c‍l‍o‍s‍e‍s #‍1” in the commit message. That way anybody will be able to refer back to any comments associated with the commit/issu.

**Comment by kseistrup** [comment]
**PS**: I just noticed in `man(1)`:

```txt
OPTIONS
   ⋮
       -D, --default
              This  option  is normally issued as the very first option and re‐
              sets man's behaviour to its default.  Its use is to  reset  those
              options that may have been set in $MANOPT.  Any options that fol‐
              low -D will have their usual effect.
```

I wonder if it could be beneficial to throw in that option as well, e.g.:

```bash
    man -D -Thtml $manpage | inject_css | link_xrefs 2>&1
```

**Comment by tkapias** [comment]
About `man -D`, I just tried and it did not work for me, without the `unset MANROFFOPT` the command still resulted in an error with my custom options.

**Comment by tkapias** [comment]
But `-D` is useful for options in the variable `MANOPT`.
On the other hand `MANROFFOPT` send options to nroff, troff, or groff from man.
So unsetting `MANROFFOPT` is good too.

**Comment by kseistrup** [comment]
Thanks for letting us know, we're getting smarter every day.

**Comment by rodarima** [comment]
I don't have -D option (I use mandoc), but I think adding `unset MANROFFOPT` should be fine.
