### ISSUE TITLE
Stray `$` when assigning variables in `serve_404()`?

### ISSUE THREAD

**Issue by kseistrup** [dillo-browser/dillo-plugin-man#2]
The `serve_404()` reads:

```sh
serve_404() {
  printf "<cmd='start_send_page' url='' '>\n"
  printf "Content-type: text/plain\r\n\r\n"
  $manpage="$1"
  $apropos="$2"
  if [ -z "$1" ]; then
    ⋮
```

Shouldn't the two assignment just read:

```sh
  manpage="$1"
  apropos="$2"
```

?

**Comment by rodarima** [comment]
Yep, that's a typo. Can you open a PR or send a patch?

**Comment by kseistrup** [comment]
> Can you open a PR or send a patch?

I'm afraid I have to decline that request, too. It is disproportionately much more work to produce and send a diff or a PR than it is to delete two dollar signs.

**Comment by rodarima** [comment]
> I'm afraid I have to decline that request, too. It is disproportionately much more work to produce and send a diff or a PR than it is to delete two dollar signs.

You can directly edit it from the browser and open a PR: https://github.com/dillo-browser/dillo-plugin-man/edit/master/man.filter.dpi

(I just did)
